name: Mention Assignees on Stale Issues

on:
  workflow_dispatch:

permissions:
  issues: write
  # pull-requests: write # Pull Requestに対する操作を行わない場合は不要

jobs:
  mention-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Mention Assignees on Stale Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 現在の日付から5分前の日付を取得
          date_threshold=$(date -d '5 minute ago' '+%Y-%m-%dT%H:%M:%SZ')
          # Issue を検索
          issues=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                         "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues?state=open&since=$date_threshold" | jq -r '.[] | @base64')
          
          # 取得したIssueの数を出力
          echo "Found $(echo $issues | wc -w) issues."
          
          for issue in $issues; do
            _jq() {
              echo ${issue} | base64 --decode | jq -r ${1}
            }

            issue_number=$(_jq '.number')
            echo "Processing issue #$issue_number."
            
            last_updated=$(_jq '.updated_at')
            assignees_login=$(echo $(_jq '.assignees') | jq -r '.[].login' | tr '\n' ' ')
            
            if [[ "$last_updated" < "$date_threshold" ]]; then
              # Issue にコメントを追加して Assignees に
