name: Mention Assignees on Stale Issues

on:
  workflow_dispatch:
  # schedule:
    # UTC 時間で 00:30 に実行 (日本時間で 09:30)
    # - cron: '30 0 * * *'

jobs:
  mention-stale-issues:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Mention Assignees on Stale Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 現在の日付から 3 日前の日付を取得
          # date_threshold=$(date -d '3 days ago' '+%Y-%m-%dT%H:%M:%SZ')
          date_threshold=$(date -d '1 minute ago' '+%Y-%m-%dT%H:%M:%SZ')
          # Issue を検索
          issues=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                         "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues?state=open&since=$date_threshold" | jq -r '.[] | @base64')
          for issue in $issues; do
            _jq() {
              echo ${issue} | base64 --decode | jq -r ${1}
            }
            
            issue_number=$(_jq '.number')
            last_updated=$(_jq '.updated_at')
            assignees_login=$(echo $(_jq '.assignees') | jq -r '.[].login' | tr '\n' ' ')
            
            if [[ "$last_updated" < "$date_threshold" ]]; then
              # Issue にコメントを追加して Assignees にメンション
              comment_body="この Issue は 3 日間更新がありません。 @$assignees_login ご確認をお願いします。"
              curl -s -H "Authorization: token $GITHUB_TOKEN" \
                   -X POST -d "{\"body\": \"$comment_body\"}" \
                   "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/$issue_number/comments"
            fi
          done
