name: Issue Reminder

on:
  schedule:
    - cron: '0 * * * *' # 毎時実行
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Run issue reminder script
        run: node ./scripts/issue-reminder.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
