name: Issue Reminder

on:
  schedule:
    - cron: '30 0 * * *' # 毎日9:30実行(UTC+9)
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @octokit/rest
        
      - name: Install additional dependencies
        run: npm install node-fetch@2.6.1

      - name: Run issue reminder script
        run: node ./.github/scripts/issue-deferred-reminder.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
